
name: Build and Deploy Cloud Function

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  setup:
    name: Setup (Fetch repo and install dependencies)
    runs-on: ubuntu-latest
    strategy:
          matrix:
            node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build
        run: npm run build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Lint
        run: npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Test
        run: npm run test
  deploy:
    name: Functions Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
      - uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: hello
          runtime: nodejs14
          source_dir: dist
          entry_point: helloWorld
          credentials: ${{ secrets.GCP_CREDENTIALS }}
