
name: Build and Deploy to GKE

on:
  release:
    types: [created]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    strategy:
          matrix:
            node-version: [14.x]
    steps:
      - name: GCP Authorization
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true
      - name: Cloud Functions Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: function-1
          runtime: nodejs10
          source_dir: /src/